# 阿里云容器镜像服务构建配置
# 此文件用于阿里云 ACR 自动构建配置

version: 1.0

build:
  dockerfile: Dockerfile
  context: /
  # 构建参数
  args:
    BUILD_TIME: ${BUILD_TIME:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
    GIT_COMMIT: ${GIT_COMMIT:-unknown}
    APP_VERSION: ${APP_VERSION:-0.0.1}

